
spring:
  datasource:
    url: jdbc:h2:mem:events
    username: events
    password: events
    driverClassName: org.h2.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true