name: "Build"

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Testes
        run: mvn test

      - name: Run Build
        run: mvn clean install