name: "Sonnar Scan"

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: SonarQube Scan
        run: | 
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=events-api \
            -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} \
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} \
            -Dsonar.qualitygate.wait=true