name: "Dev - Test"

on:
  push:
    branches:
      - main

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Testes
        run: mvn test

      - name: Run Build
        run: mvn clean install

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: "src/"
          projectKey: "events-api"