name: "Dev - Test"

on:
  push:
    branches:
      - main

jobs:
  dev-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Unit & Integration Tests
        run: mvn test

      - name: SonarQube Scan
        run: mvn clean verify sonar:sonar \
                -Dsonar.projectKey=events-api \
                -Dsonar.host.url=http://159.223.195.60:9000 \
                -Dsonar.login=sqa_e55b54a5c77d31640762cf42817f79da86091759 \
                -Dsonar.qualitygate.wait=true